"""
Small DB-API compatibility layer for the CRM's PostgreSQL connection.

The existing application was written against sqlite3. This module preserves
the cursor and row behavior used throughout the CRM while translating qmark
parameters and the small set of SQLite SQL constructs still emitted by legacy
initialization code.
"""

from __future__ import annotations

import re
from collections.abc import Iterator, Mapping, Sequence
from typing import Any

import psycopg


class HybridRow(Mapping[str, Any], Sequence[Any]):
    """Row supporting both row[0] and row["column"], like sqlite3.Row."""

    def __init__(
        self,
        columns: Sequence[str],
        values: Sequence[Any],
    ) -> None:
        self._columns = tuple(columns)
        self._values = tuple(values)
        self._lookup = {
            column: index
            for index, column in enumerate(self._columns)
        }

    def __getitem__(self, key: int | slice | str) -> Any:
        if isinstance(key, str):
            return self._values[self._lookup[key]]

        return self._values[key]

    def __iter__(self) -> Iterator[Any]:
        return iter(self._values)

    def __len__(self) -> int:
        return len(self._values)

    def keys(self) -> tuple[str, ...]:
        return self._columns

    def values(self) -> tuple[Any, ...]:
        return self._values

    def items(self) -> tuple[tuple[str, Any], ...]:
        return tuple(zip(self._columns, self._values))


def _replace_qmark_parameters(statement: str) -> str:
    result: list[str] = []
    quote: str | None = None
    index = 0

    while index < len(statement):
        character = statement[index]

        if quote is not None:
            result.append(character)

            if character == quote:
                if (
                    index + 1 < len(statement)
                    and statement[index + 1] == quote
                ):
                    result.append(statement[index + 1])
                    index += 1
                else:
                    quote = None

        elif character in ("'", '"'):
            quote = character
            result.append(character)

        elif character == "?":
            result.append("%s")

        else:
            result.append(character)

        index += 1

    return "".join(result)


def _convert_insert_or_ignore(statement: str) -> str:
    converted = re.sub(
        r"\bINSERT\s+OR\s+IGNORE\s+INTO\b",
        "INSERT INTO",
        statement,
        count=1,
        flags=re.IGNORECASE,
    )

    if converted == statement:
        return statement

    return converted.rstrip().rstrip(";") + " ON CONFLICT DO NOTHING"


def _convert_create_table(statement: str) -> str:
    converted = re.sub(
        r"\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b",
        "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        statement,
        flags=re.IGNORECASE,
    )
    converted = re.sub(
        r"\bREAL\b",
        "DOUBLE PRECISION",
        converted,
        flags=re.IGNORECASE,
    )
    converted = re.sub(
        r"\bTIMESTAMP\b",
        "TIMESTAMPTZ",
        converted,
        flags=re.IGNORECASE,
    )

    return converted


def translate_sql(statement: str) -> tuple[str, str | None]:
    stripped = statement.strip()
    pragma_match = re.fullmatch(
        r"PRAGMA\s+table_info\s*\(\s*([A-Za-z_][A-Za-z0-9_]*)\s*\)\s*;?",
        stripped,
        flags=re.IGNORECASE,
    )

    if pragma_match:
        table = pragma_match.group(1)

        return (
            """
            SELECT
                ordinal_position - 1 AS cid,
                column_name AS name,
                data_type AS type,
                CASE WHEN is_nullable = 'NO' THEN 1 ELSE 0 END AS notnull,
                column_default AS dflt_value,
                CASE WHEN column_name IN (
                    SELECT key_column_usage.column_name
                    FROM information_schema.table_constraints
                    JOIN information_schema.key_column_usage
                      ON table_constraints.constraint_name =
                         key_column_usage.constraint_name
                     AND table_constraints.table_schema =
                         key_column_usage.table_schema
                    WHERE table_constraints.constraint_type = 'PRIMARY KEY'
                      AND table_constraints.table_schema = 'public'
                      AND table_constraints.table_name = %s
                ) THEN 1 ELSE 0 END AS pk
            FROM information_schema.columns
            WHERE table_schema = 'public'
              AND table_name = %s
            ORDER BY ordinal_position
            """,
            table,
        )

    converted = _convert_insert_or_ignore(statement)

    if re.match(
        r"^\s*CREATE\s+TABLE\b",
        converted,
        flags=re.IGNORECASE,
    ):
        converted = _convert_create_table(converted)

    converted = _replace_qmark_parameters(converted)

    return converted, None


class PostgresCursor:
    def __init__(
        self,
        connection: "PostgresConnection",
        cursor: psycopg.Cursor[Any],
    ) -> None:
        self._connection = connection
        self._cursor = cursor
        self._lastrowid: int | None = None
        self._insert_table: str | None = None

    @property
    def description(self) -> Any:
        return self._cursor.description

    @property
    def rowcount(self) -> int:
        return self._cursor.rowcount

    @property
    def lastrowid(self) -> int | None:
        if self._lastrowid is not None:
            return self._lastrowid

        if self._insert_table is None:
            return None

        with self._connection._connection.cursor() as cursor:
            cursor.execute(
                "SELECT pg_get_serial_sequence(%s, 'id')",
                (f"public.{self._insert_table}",),
            )
            row = cursor.fetchone()
            sequence = row[0] if row else None

            if sequence is None:
                return None

            cursor.execute(
                "SELECT currval(%s)",
                (sequence,),
            )
            row = cursor.fetchone()

            if row is not None:
                self._lastrowid = int(row[0])

        return self._lastrowid

    def execute(
        self,
        statement: str,
        params: Sequence[Any] | Mapping[str, Any] = (),
    ) -> "PostgresCursor":
        converted, pragma_table = translate_sql(statement)

        if pragma_table is not None:
            params = (pragma_table, pragma_table)

        insert_match = re.match(
            r"^\s*INSERT(?:\s+OR\s+\w+)?\s+INTO\s+"
            r"[\"']?([A-Za-z_][A-Za-z0-9_]*)",
            statement,
            flags=re.IGNORECASE,
        )
        self._insert_table = (
            insert_match.group(1)
            if insert_match
            else None
        )
        self._lastrowid = None
        if params:
            self._cursor.execute(converted, params)
        else:
            self._cursor.execute(converted)

        return self

    def executemany(
        self,
        statement: str,
        params_seq: Sequence[Sequence[Any]],
    ) -> "PostgresCursor":
        converted, pragma_table = translate_sql(statement)

        if pragma_table is not None:
            raise ValueError(
                "PRAGMA table_info cannot be used with executemany()."
            )

        self._cursor.executemany(converted, params_seq)
        self._insert_table = None
        self._lastrowid = None

        return self

    def _columns(self) -> tuple[str, ...]:
        if self._cursor.description is None:
            return ()

        return tuple(
            str(column.name)
            for column in self._cursor.description
        )

    def _wrap(self, row: Sequence[Any] | None) -> HybridRow | None:
        if row is None:
            return None

        return HybridRow(self._columns(), row)

    def fetchone(self) -> HybridRow | None:
        return self._wrap(self._cursor.fetchone())

    def fetchmany(self, size: int = 1) -> list[HybridRow]:
        columns = self._columns()

        return [
            HybridRow(columns, row)
            for row in self._cursor.fetchmany(size)
        ]

    def fetchall(self) -> list[HybridRow]:
        columns = self._columns()

        return [
            HybridRow(columns, row)
            for row in self._cursor.fetchall()
        ]

    def close(self) -> None:
        self._cursor.close()

    def __iter__(self) -> Iterator[HybridRow]:
        columns = self._columns()

        for row in self._cursor:
            yield HybridRow(columns, row)

    def __enter__(self) -> "PostgresCursor":
        return self

    def __exit__(
        self,
        exc_type: Any,
        exc_value: Any,
        traceback: Any,
    ) -> None:
        self.close()


class PostgresConnection:
    def __init__(
        self,
        connection: psycopg.Connection[Any],
    ) -> None:
        self._connection = connection

    def cursor(self) -> PostgresCursor:
        return PostgresCursor(
            self,
            self._connection.cursor(),
        )

    def execute(
        self,
        statement: str,
        params: Sequence[Any] | Mapping[str, Any] = (),
    ) -> PostgresCursor:
        cursor = self.cursor()

        try:
            return cursor.execute(statement, params)
        except Exception:
            cursor.close()
            raise

    def commit(self) -> None:
        self._connection.commit()

    def rollback(self) -> None:
        self._connection.rollback()

    def close(self) -> None:
        self._connection.close()

    def __enter__(self) -> "PostgresConnection":
        return self

    def __exit__(
        self,
        exc_type: Any,
        exc_value: Any,
        traceback: Any,
    ) -> None:
        if exc_type is None:
            self.commit()
        else:
            self.rollback()

        self.close()


def connect(settings: Mapping[str, Any]) -> PostgresConnection:
    connection = psycopg.connect(
        host=str(settings["host"]),
        port=int(settings.get("port", 5432)),
        dbname=str(settings.get("dbname", "postgres")),
        user=str(settings["user"]),
        password=str(settings["password"]),
        sslmode=str(settings.get("sslmode", "require")),
        connect_timeout=30,
    )

    return PostgresConnection(connection)
